apiVersion: 1

datasources:
  - name: PostGIS
    uid: PostGIS
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: afl_gis
    user: afl
    secureJsonData:
      password: afl
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true

  - name: OSM
    uid: OSM
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    database: osm
    user: afl_osm
    secureJsonData:
      password: afl_osm_2024
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
