# Copyright 2025 Ralph Lemke
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Handler-gap scaffolder.

When a natural-language request needs a capability no existing facet provides,
the catalog preflight (or ``fw_validate``) flags a *named gap*. This module turns
that gap into **review-ready scaffolds** — an FFL event-facet declaration, a
Python handler stub (with registration), and a pytest stub — so a service-provider
(or Claude) can implement + review + register the new handler. It never deploys
anything: capability extension goes through human review.

See ``docs/architecture/extending-with-new-handlers.md`` for the full process.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


@dataclass
class FacetSpec:
    """The signature of a facet to scaffold."""

    qualified_name: str  # e.g. "osm.Filters.FilterGeoJSONByTagContains"
    params: list[tuple[str, str]] = field(default_factory=list)  # [(name, type)]
    returns: list[tuple[str, str]] = field(default_factory=list)  # [(field, type)]
    doc: str = ""

    @property
    def namespace(self) -> str:
        return self.qualified_name.rsplit(".", 1)[0] if "." in self.qualified_name else ""

    @property
    def short_name(self) -> str:
        return self.qualified_name.rsplit(".", 1)[-1]

    @property
    def module_stem(self) -> str:
        # CamelCase -> snake_case (acronym-aware: GeoJSON -> geo_json)
        s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", self.short_name)
        s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
        return f"{s.lower()}_handler"


def parse_pairs(spec: str) -> list[tuple[str, str]]:
    """Parse ``"name:Type,other:Type2"`` -> ``[("name","Type"), ...]``."""
    out: list[tuple[str, str]] = []
    for part in (p.strip() for p in spec.split(",")):
        if not part:
            continue
        name, _, typ = part.partition(":")
        out.append((name.strip(), (typ.strip() or "String")))
    return out


# ---------------------------------------------------------------------------
# Gap detection
# ---------------------------------------------------------------------------


def detect_missing_facets(
    program_dict: dict, entry_workflow: str, registered: set[str]
) -> list[str]:
    """Event facets reachable from ``entry_workflow`` that have no registered
    handler — i.e. the gaps a run would hit. ``registered`` is the set of facet
    names the fleet advertises (from ``list_handler_registrations``)."""
    from facetwork.catalog.service import _entry_event_facets

    needed = _entry_event_facets(program_dict, entry_workflow)
    short = {r.rsplit(".", 1)[-1] for r in registered}
    return sorted(q for q in needed if q not in registered and q.rsplit(".", 1)[-1] not in short)


# ---------------------------------------------------------------------------
# Scaffold generators
# ---------------------------------------------------------------------------


def scaffold_facet(spec: FacetSpec) -> str:
    """The FFL ``event facet`` declaration (the typed contract)."""
    params = ", ".join(f"{n}: {t}" for n, t in spec.params) or ""
    returns = ", ".join(f"{n}: {t}" for n, t in spec.returns) or "ok: Boolean"
    doc = spec.doc or f"TODO: describe what {spec.short_name} does."
    return (
        f"// Add inside `namespace {spec.namespace} {{ ... }}` in the package's FFL\n"
        f"// (e.g. handlers/<area>/ffl/<area>.ffl). Keep types in sync with the handler.\n"
        f"/** {doc} */\n"
        f"event facet {spec.short_name}({params}) => ({returns})\n"
    )


def scaffold_handler(spec: FacetSpec) -> str:
    """A standalone Python handler stub with RegistryRunner registration."""
    reads = "\n".join(f'    {n} = payload.get("{n}")' for n, _ in spec.params) or "    pass"
    ret_names = ", ".join(n for n, _ in spec.returns) or "ok"
    first_ret = spec.returns[0][0] if spec.returns else "ok"
    ret_hint = ", ".join(f'"{n}": ...' for n, _ in spec.returns) or '"ok": True'
    return f'''"""Handler for {spec.qualified_name} — SCAFFOLD. Implement + review before registering.

Generated by `fw ffl scaffold`. ``handle`` raises NotImplementedError until
filled in. For a domain pipeline, put reusable logic in the package's
`_<pkg>_tools/` and call it here (see agent-spec/tools-pattern.agent-spec.yaml).
"""

from __future__ import annotations

import os


def handle(payload: dict) -> dict:
    """Implements {spec.qualified_name}.

    Reads the FFL facet params from ``payload`` and returns a dict whose keys
    match the FFL return clause: {ret_names}. ``payload`` also carries runtime keys
    like ``_step_log`` (progress) and ``_task_heartbeat`` (call periodically during
    long work).
    """
    step_log = payload.get("_step_log")
{reads}

    # TODO: implement the operation, then return a dict matching the FFL return
    # clause, e.g.:  return {{"{first_ret}": {{ {ret_hint} }}}}
    raise NotImplementedError("scaffold: implement {spec.qualified_name}")


def register_handlers(runner) -> None:
    """Register this handler with a RegistryRunner (writes a HandlerRegistration)."""
    runner.register_handler(
        facet_name="{spec.qualified_name}",
        module_uri=f"file://{{os.path.abspath(__file__)}}",
        entrypoint="handle",
    )
'''


def scaffold_test(spec: FacetSpec) -> str:
    """A pytest stub asserting the contract (replace the NotImplementedError check)."""
    sample = ", ".join(f'"{n}": ...' for n, _ in spec.params)
    return f'''"""Contract test for {spec.qualified_name} — SCAFFOLD."""

import pytest

from {spec.module_stem} import handle


def test_{spec.short_name.lower()}_not_yet_implemented():
    # Remove this once `handle` is implemented; then assert the real contract:
    #   result = handle({{{sample}}})
    #   assert result["{spec.returns[0][0] if spec.returns else "ok"}"] ...
    with pytest.raises(NotImplementedError):
        handle({{{sample}}})
'''


def review_checklist(spec: FacetSpec) -> str:
    """The human-facing steps to take the scaffold to a deployed handler."""
    return f"""# Review + deploy checklist — {spec.qualified_name}

This is NEW executable capability (arbitrary Python on the fleet), so it is a
reviewed code contribution to the handler package — not a catalog-only change.

1. [ ] Implement `handle()` in {spec.module_stem}.py (fill the body; put reusable
       logic in the package's `_<pkg>_tools/` per agent-spec/tools-pattern).
2. [ ] Add the `event facet` declaration to the package's FFL (see the .ffl scaffold),
       keeping param/return types in sync with the handler.
3. [ ] Wire registration: either keep this module's `register_handlers(runner)`, or
       add `{spec.short_name}` to the area's FACETS list + dispatch (match the
       package's existing pattern, e.g. road_handlers.py / filter_handlers.py).
4. [ ] Write the real test (replace the NotImplementedError stub).
5. [ ] `fw_validate` the package FFL (the new facet resolves) + run the tests.
6. [ ] Code review + commit to the handler package (the human gate for new code).
7. [ ] Deploy: `pip install -e <pkg>` + (re)start the runner so it registers the
       handler. Confirm with `fw runner list` / the catalog preflight.
8. [ ] `fw ffl catalog import-package <pkg>` to expose the facet in the catalog
       library, then author/validate/publish the workflow that uses it.
"""
